### ISSUE TITLE
Is longform conversion from a text file working properly via read.py? (--kv_cache unrecognized)

### ISSUE THREAD

**Issue by kylereinfeld** [152334H/tortoise-tts-fast#11]
I'm getting an "unrecognized arguments" error when I try to run read.py with --kv_cache.

**Comment by pepinu** [comment]
add on the [line 26 in read.py ](https://github.com/152334H/tortoise-tts-fast/blob/main/tortoise/read.py#L26 )
a line like
```
parser.add_argument('--kv-cache', type=bool, help='Whether or not to use kv_cache. Defaults to true.', default=True)
```
then [this line](https://github.com/152334H/tortoise-tts-fast/blob/main/tortoise/read.py#L28) should be modified to

```
tts = TextToSpeech(models_dir=args.model_dir, kv_cache=args.kv_cache)
```

and it should work, if it does feel free to do a PR for that

**Comment by 152334H** [comment]
Ah, I haven't done any changes in any of the CLI code files apart from `do_tts.py`, apologies.

**Comment by 152334H** [comment]
addressed [here](https://github.com/152334H/tortoise-tts-fast/commit/f701c4253872ff154acc98586b9d680ae300107c). Please reopen this issue if something was broken by the commit.
