### ISSUE TITLE
module 'torch.nn.utils.parametrizations' has no attribute 'weight_norm'

### ISSUE THREAD

**Issue by MrVtR** [152334H/tortoise-tts-fast#132]
I'm trying to run tts-fast in Anaconda and it's not working, it's returning this error when I activate the Web UI
Does anyone know if there is a solution for this? I followed the setup instructions in this repository correctly

![image](https://github.com/152334H/tortoise-tts-fast/assets/30987772/70431744-e98e-48af-be46-584ab1f651ff)

**Comment by JeffPlsFix** [comment]
What version PyTorch are you using?

you could try using an earlier Voicefixer package:
```
pip3 install voicefixer==0.1.2
```

**Comment by Dafterfly** [comment]
I fixed it by running the torch installation line after running all the installation steps

**Comment by MrVtR** [comment]
> I fixed it by running the torch installation line after running all the installation steps

This line here?
`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
`
Because if so, it didn't work, since it's the same version of the torch dependencies that the repo installed on `pip install -e .`

**Comment by MrVtR** [comment]
> What version PyTorch are you using?
> 
> you could try using an earlier Voicefixer package:
> 
> ```
> pip3 install voicefixer==0.1.2
> ```

I'm using torch 1.13.1, the version that is installed with the repo instructions

Edit: Seems that using the `pip3 install voicefixer==0.1.2` fix the torch error, but now I have this one when I try to load the web UI:

```

RuntimeError: Error(s) in loading state_dict for UnifiedVoice: Unexpected key(s) in state_dict: "gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias".
Traceback:
File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\scripts\app.py", line 278, in <module>
    main()
File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\scripts\app.py", line 180, in main
    tts = load_model(model_dir, high_vram, kv_cache, ar_checkpoint, diff_checkpoint)
File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\app_utils\funcs.py", line 29, in load_model
    return TextToSpeech(
File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\tortoise\api.py", line 271, in __init__
    self.autoregressive.load_state_dict(torch.load(ar_path))
File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
```

**Comment by MrVtR** [comment]
> > What version PyTorch are you using?
> > you could try using an earlier Voicefixer package:
> > ```
> > pip3 install voicefixer==0.1.2
> > ```
> 
> I'm using torch 1.13.1, the version that is installed with the repo instructions
> 
> Edit: Seems that using the `pip3 install voicefixer==0.1.2` fix the torch error, but now I have this one when I try to load the web UI:
> 
> ```
> 
> RuntimeError: Error(s) in loading state_dict for UnifiedVoice: Unexpected key(s) in state_dict: "gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias".
> Traceback:
> File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
>     exec(code, module.__dict__)
> File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\scripts\app.py", line 278, in <module>
>     main()
> File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\scripts\app.py", line 180, in main
>     tts = load_model(model_dir, high_vram, kv_cache, ar_checkpoint, diff_checkpoint)
> File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
>     return cached_func(*args, **kwargs)
> File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
>     return self._get_or_create_cached_value(args, kwargs)
> File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
>     return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
> File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
>     computed_value = self._info.func(*func_args, **func_kwargs)
> File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\app_utils\funcs.py", line 29, in load_model
>     return TextToSpeech(
> File "C:\Users\vitor\Desktop\tts\tortoise-tts-fast\tortoise\api.py", line 271, in __init__
>     self.autoregressive.load_state_dict(torch.load(ar_path))
> File "C:\Users\vitor\miniconda3\envs\ttts-fast\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> ```

#109  Applying the solution found on this other issue made the app work without anymore errors, I'm closing the issue here, thanks all!
