### ISSUE TITLE
Download models once

### ISSUE THREAD

**Issue by demianvle** [152334H/tortoise-tts-fast#18]
First, thank you for working on this. I believe its awesome you are trying to keep this open and available locally for users who don´t want to depend on cloud, third party services. 

My request/questions:  can you follow a similar path to Automatic1111 SD´s where models are downloaded and added to a folder once, manually, vs the models being downloaded every time TTS runs? I also like the webui idea, I just would prefer if running tts-fast could be done without internet connection. 

Thanks!

**Comment by demianvle** [comment]
I´m also getting this: 
AppData\Local\Programs\Python\Python310\lib\site-packages\torch\amp\autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
  
 I have a GTX1060, 4gb, I was still able to generate some audio but it ran on the CPU and took forever. could this be on my end?

**Comment by 152334H** [comment]
> My request/questions: can you follow a similar path to Automatic1111 SD´s where models are downloaded and added to a folder once, manually, vs the models being downloaded every time TTS runs?

uhhhhhhhhhhhh this is supposed to happen by default. Are you using do_tts.py or something else?

> UserWarning: User provided device_type of 'cuda', but CUDA is not available.

Either CUDA is not installed or you installed the pytorch package without CUDA.

**Comment by demianvle** [comment]
> > My request/questions: can you follow a similar path to Automatic1111 SD´s where models are downloaded and added to a folder once, manually, vs the models being downloaded every time TTS runs?
> 
> uhhhhhhhhhhhh this is supposed to happen by default. Are you using do_tts.py or something else?
> (This I guess I didn´t check fine, seems to be ok)
> > UserWarning: User provided device_type of 'cuda', but CUDA is not available.
> 
> Either CUDA is not installed or you installed the pytorch package without CUDA. If it's the latter, check the pytorch website on instructions to install pytorch with CUDA.

I reinstalled Cuda, uninstalled pytorch and reinstalled and its working now. Sorry to bother :p 
Thank you and keep up the great work. I think keeping AI tools open and locally run is key for our future. I´m only sorry I can´t contribute/help much. I will download test and spread the word for sure.
