### ISSUE TITLE
Unify inference scripts

### ISSUE THREAD

**Issue by 152334H** [152334H/tortoise-tts-fast#21]
There's currently:
 - the API (`tortoise/api.py`)
 - the `tortoise/do_tts.py` script
 - the `tortoise/read.py` script
 - the `scripts/tortoise_tts.py` script
 - the `app.py` webui
 - the untouched colab `.ipynb`

This is too many scripts. Worse still, many of these scripts contain duplicated code to, e.g. split voices or write files.

I want:
- [ ] a meta-inference script that handles all the shared functionality for running tortoise (currently: `scripts/inference.py`)
- [ ] a **single** CLI script (most likely cut from `tortoise_tts.py`)
- [ ] a **single** webui, that the colab notebook also uses

Everything else should either be scrapped or converted to thin wrappers around the main scripts.

**Comment by Ryu1845** [comment]
I actually started doing this the other day. I was planning to refactor the code a little before finishing that, but I'll do it now.

**Comment by Ryu1845** [comment]
What do you think of using an external library like [Typed Argument Parser](https://github.com/swansonk14/typed-argument-parser)?

**Comment by 152334H** [comment]
> I actually started doing this the other day. I was planning to refactor the code a little before finishing that, but I can do it now if you want.

Depends on how upset you are by the changes I already made earlier

> What do you think of using an external library like [Typed Argument Parser](https://github.com/swansonk14/typed-argument-parser)?

I've never tried it before, if you know it works well then go for it

**Comment by Ryu1845** [comment]
Done with #27
