### ISSUE TITLE
A better way to deal with package management?

### ISSUE THREAD

**Issue by Ryu1845** [152334H/tortoise-tts-fast#23]
Currently, it looks like the chosen mechanism is to lock the version to a `requirements-version.txt` file. 
I think adding support for a proper dependency management tool like poetry or [pyflow](https://github.com/David-OConnor/pyflow) could be nice. Or maybe at least use something like https://github.com/jazzband/pip-tools/ to correctly lock them using hashes.
P.S. I'd be happy to add one myself :smile:

**Comment by 152334H** [comment]
I will probably not use the new dependency management system, if it is added. I have not used any of the mentioned tooling before and will not be capable of maintaining it.

I do not see any inherent problems with adding it, though, since I doubt it would break anything

**Comment by Ryu1845** [comment]
Alright, I'll make a PR for it. I think that would be a useful tool to make publishing the project on PyPI eventually too.

**Comment by 152334H** [comment]
> since I doubt it would break anything

This was incredibly wrong

Making a new env now for this project specifically :)

**Comment by Ryu1845** [comment]
What went wrong?

**Comment by 152334H** [comment]
I was sharing the env with other projects, which was a huge problem for creating a good requirements.txt file

Also, streamlit/voicefixer was missing from pyproject.toml, and the former needed a change to the python version

But I made a new venv so it should be fine now

**Comment by Ryu1845** [comment]
Ok nice. I guess I can close this issue now?
