### ISSUE TITLE
Wait 1 week to see if anyone complains about voicefixer

### ISSUE THREAD

**Issue by 152334H** [152334H/tortoise-tts-fast#26]
I'm pretty sure no one is going to do that, but just in case.

**Comment by rikabi89** [comment]
how does it work in this context, does it automatically "clean" the outputs? I can't see any visible toggle or option to use it.

**Comment by rikabi89** [comment]
It would seem it doing the cleaning automatically. Anyway I can toggle this off unfortuntely it's making the samples sound a lot worse.

**Comment by 152334H** [comment]
addressed in https://github.com/152334H/tortoise-tts-fast/commit/f5bf651420d151b08fe185b7db3293d5bfb778d1, i added a checkbox && cli flag for the webui and scripts respectively :)

**Comment by Ryu1845** [comment]
Time to close this?
