### ISSUE TITLE
'streamlit' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by rbychn** [152334H/tortoise-tts-fast#28]
after fresh install, that's the error

**Comment by rbychn** [comment]
after manually installing streamlit and running app.py, I get

`ModuleNotFoundError: No module named 'chardet'`

**Comment by rbychn** [comment]
after manually adding chardet and running app.py, I get the following in the browser

`ModuleNotFoundError: No module named 'voicefixer'`

**Comment by rikabi89** [comment]
> after manually adding chardet and running app.py, I get the following in the browser
> 
> `ModuleNotFoundError: No module named 'voicefixer'`

try `pip install voicefixer`

**Comment by 152334H** [comment]
I don't actually have `chardet` installed, so I'm fairly confused about that part.

as a stopgap measure, i've just dumped streamlit and voicefixer into the requirements file, while I try to wrangle a new python env

**Comment by 152334H** [comment]
properly addressed in https://github.com/152334H/tortoise-tts-fast/commit/9711b2ce76c1d1c7b40346fccd27a145ddde6422
