### ISSUE TITLE
ImportError and llvmlite

### ISSUE THREAD

**Issue by KaleidoscopicPrism** [152334H/tortoise-tts-fast#29]
Why does this happen when I try to generate?

Traceback (most recent call last):
  File "E:\tortoise-tts-fast\tortoise\do_tts.py", line 9, in <module>
    from api import TextToSpeech
  File "E:\tortoise-tts-fast\tortoise\api.py", line 14, in <module>
    from tortoise.models.arch_util import TorchMelSpectrogram
  File "E:\Anaconda3\lib\site-packages\tortoise\models.py", line 25, in <module>
    from tortoise import connections
ImportError: cannot import name 'connections' from 'tortoise' (unknown location)

And why does this happen when I install requirements.txt and pip install -e .

ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by 152334H** [comment]
see [here](https://stackoverflow.com/questions/58766671/cannot-install-librosa-python-how-can-i-uninstall-llvmlite)

> `pip install llvmlite --ignore installed`

you can also install [poetry](https://python-poetry.org/docs/) and run it that way, but I assume that is too complex for casual users

**Comment by KaleidoscopicPrism** [comment]
> see [here](https://stackoverflow.com/questions/58766671/cannot-install-librosa-python-how-can-i-uninstall-llvmlite)
> 
> > `pip install llvmlite --ignore installed`
> 
> you can also install [poetry](https://python-poetry.org/docs/) and run it that way, but I assume that is too complex for casual users

Now this happens:

E:\Anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\tortoise-tts-fast\tortoise\do_tts.py:11 in <module>                                           │
│                                                                                                  │
│    8 import torch                                                                                │
│    9 from api import TextToSpeech                                                                │
│   10 from base_argparser import ap, nullable_kwargs                                              │
│ ❱ 11 from inference import save_gen_with_voicefix                                                │
│   12 from utils.audio import load_voices                                                         │
│   13                                                                                             │
│   14                                                                                             │
│                                                                                                  │
│ E:\tortoise-tts-fast\tortoise\inference.py:162 in <module>                                       │
│                                                                                                  │
│   159                                                                                            │
│   160 from voicefixer import VoiceFixer                                                          │
│   161                                                                                            │
│ ❱ 162 vfixer = VoiceFixer()                                                                      │
│   163                                                                                            │
│   164                                                                                            │
│   165 def save_gen_with_voicefix(g, fpath, squeeze=True, voicefixer=True):                       │
│                                                                                                  │
│ E:\Anaconda3\lib\site-packages\voicefixer\base.py:24 in __init__                                 │
│                                                                                                  │
│    21 │   │   │   │   │   │   │   │   By default the checkpoint should be download automatical   │
│    22 │   │   │   │   │   │   │   │   But don't worry! Alternatively you can download it direc   │
│    23 │   │   self._model.load_state_dict(                                                       │
│ ❱  24 │   │   │   torch.load(                                                                    │
│    25 │   │   │   │   self.analysis_module_ckpt                                                  │
│    26 │   │   │   )                                                                              │
│    27 │   │   )                                                                                  │
│                                                                                                  │
│ E:\Anaconda3\lib\site-packages\torch\serialization.py:777 in load                                │
│                                                                                                  │
│    774 │   │   │   # If we want to actually tail call to torch.jit.load, we need to              │
│    775 │   │   │   # reset back to the original position.                                        │
│    776 │   │   │   orig_position = opened_file.tell()                                            │
│ ❱  777 │   │   │   with _open_zipfile_reader(opened_file) as opened_zipfile:                     │
│    778 │   │   │   │   if _is_torchscript_zip(opened_zipfile):                                   │
│    779 │   │   │   │   │   warnings.warn("'torch.load' received a zip file that looks like a To  │
│    780 │   │   │   │   │   │   │   │     " dispatching to 'torch.jit.load' (call 'torch.jit.loa  │
│                                                                                                  │
│ E:\Anaconda3\lib\site-packages\torch\serialization.py:282 in __init__                            │
│                                                                                                  │
│    279                                                                                           │
│    280 class _open_zipfile_reader(_opener):                                                      │
│    281 │   def __init__(self, name_or_buffer) -> None:                                           │
│ ❱  282 │   │   super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_bu  │
│    283                                                                                           │
│    284                                                                                           │
│    285 class _open_zipfile_writer_file(_opener):                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by 152334H** [comment]
did you cancel the model download for voicefixer at some point

**Comment by KaleidoscopicPrism** [comment]
i think so

**Comment by KaleidoscopicPrism** [comment]
i'm just gonna reinstall tortoise

**Comment by KaleidoscopicPrism** [comment]
> i'm just gonna reinstall tortoise

it did not work

**Comment by 152334H** [comment]
your libraries are screwed, you need a fresh python environment (and also need to nuke wherever the partially downloaded voicefixer model file is)

**Comment by KaleidoscopicPrism** [comment]
how would i do as such?

**Comment by KaleidoscopicPrism** [comment]
i've created a new environment with python 3.9.1 in anaconda3 and deleted the voicefixer and voicefixer cmd file in the scripts folder before i did that

**Comment by KaleidoscopicPrism** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\tortoise-tts-fast\tortoise\do_tts.py:11 in <module>                                           │
│                                                                                                  │
│    8 import torch                                                                                │
│    9 from api import TextToSpeech                                                                │
│   10 from base_argparser import ap, nullable_kwargs                                              │
│ ❱ 11 from inference import save_gen_with_voicefix                                                │
│   12 from utils.audio import load_voices                                                         │
│   13                                                                                             │
│   14                                                                                             │
│                                                                                                  │
│ E:\tortoise-tts-fast\tortoise\inference.py:167 in <module>                                       │
│                                                                                                  │
│   164                                                                                            │
│   165 from voicefixer import VoiceFixer                                                          │
│   166                                                                                            │
│ ❱ 167 vfixer = VoiceFixer()                                                                      │
│   168                                                                                            │
│   169                                                                                            │
│   170 def save_gen_with_voicefix(g, fpath, squeeze=True, voicefixer=True):                       │
│                                                                                                  │
│ E:\Anaconda3\envs\Fuck\lib\site-packages\voicefixer\base.py:24 in __init__                       │
│                                                                                                  │
│    21 │   │   │   │   │   │   │   │   By default the checkpoint should be download automatical   │
│    22 │   │   │   │   │   │   │   │   But don't worry! Alternatively you can download it direc   │
│    23 │   │   self._model.load_state_dict(                                                       │
│ ❱  24 │   │   │   torch.load(                                                                    │
│    25 │   │   │   │   self.analysis_module_ckpt                                                  │
│    26 │   │   │   )                                                                              │
│    27 │   │   )                                                                                  │
│                                                                                                  │
│ E:\Anaconda3\envs\Fuck\lib\site-packages\torch\serialization.py:777 in load                      │
│                                                                                                  │
│    774 │   │   │   # If we want to actually tail call to torch.jit.load, we need to              │
│    775 │   │   │   # reset back to the original position.                                        │
│    776 │   │   │   orig_position = opened_file.tell()                                            │
│ ❱  777 │   │   │   with _open_zipfile_reader(opened_file) as opened_zipfile:                     │
│    778 │   │   │   │   if _is_torchscript_zip(opened_zipfile):                                   │
│    779 │   │   │   │   │   warnings.warn("'torch.load' received a zip file that looks like a To  │
│    780 │   │   │   │   │   │   │   │     " dispatching to 'torch.jit.load' (call 'torch.jit.loa  │
│                                                                                                  │
│ E:\Anaconda3\envs\Fuck\lib\site-packages\torch\serialization.py:282 in __init__                  │
│                                                                                                  │
│    279                                                                                           │
│    280 class _open_zipfile_reader(_opener):                                                      │
│    281 │   def __init__(self, name_or_buffer) -> None:                                           │
│ ❱  282 │   │   super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_bu  │
│    283                                                                                           │
│    284                                                                                           │
│    285 class _open_zipfile_writer_file(_opener):                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by KaleidoscopicPrism** [comment]
> your libraries are screwed, you need a fresh python environment (and also need to nuke wherever the partially downloaded voicefixer model file is)

I've repeated the process but with python 3.8 and it still hasn't worked.
