### ISSUE TITLE
read.py fails at torchaudio tensor dimension check [Expected 2D Tensor, got 3D.]

### ISSUE THREAD

**Issue by KareshiKraise** [152334H/tortoise-tts-fast#33]
a simple "python tortoise/read.py --voice random --preset ultra_fast" will fail as following.

Running on an RTX 3080

![WindowsTerminal_HAkRZK1ydG](https://user-images.githubusercontent.com/11684538/220747360-259bb034-8250-422c-9690-11c49777a6d1.png)

**Comment by 152334H** [comment]
fixed, sorry
