### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by KaleidoscopicPrism** [152334H/tortoise-tts-fast#36]
I stopped the voicefixer download accidentally and now this happens. I tried what you said last time but it didn't help (created a new environment and deleted the voicefixer model files.) I'm using Anaconda3

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\tortoise-tts-fast\tortoise\do_tts.py:11 in │
│ │
│ 8 import torch │
│ 9 from api import TextToSpeech │
│ 10 from base_argparser import ap, nullable_kwargs │
│ ❱ 11 from inference import save_gen_with_voicefix │
│ 12 from utils.audio import load_voices │
│ 13 │
│ 14 │
│ │
│ E:\tortoise-tts-fast\tortoise\inference.py:167 in │
│ │
│ 164 │
│ 165 from voicefixer import VoiceFixer │
│ 166 │
│ ❱ 167 vfixer = VoiceFixer() │
│ 168 │
│ 169 │
│ 170 def save_gen_with_voicefix(g, fpath, squeeze=True, voicefixer=True): │
│ │
│ E:\Anaconda3\envs\Fuck\lib\site-packages\voicefixer\base.py:24 in init │
│ │
│ 21 │ │ │ │ │ │ │ │ By default the checkpoint should be download automatical │
│ 22 │ │ │ │ │ │ │ │ But don't worry! Alternatively you can download it direc │
│ 23 │ │ self._model.load_state_dict( │
│ ❱ 24 │ │ │ torch.load( │
│ 25 │ │ │ │ self.analysis_module_ckpt │
│ 26 │ │ │ ) │
│ 27 │ │ ) │
│ │
│ E:\Anaconda3\envs\Fuck\lib\site-packages\torch\serialization.py:777 in load │
│ │
│ 774 │ │ │ # If we want to actually tail call to torch.jit.load, we need to │
│ 775 │ │ │ # reset back to the original position. │
│ 776 │ │ │ orig_position = opened_file.tell() │
│ ❱ 777 │ │ │ with _open_zipfile_reader(opened_file) as opened_zipfile: │
│ 778 │ │ │ │ if _is_torchscript_zip(opened_zipfile): │
│ 779 │ │ │ │ │ warnings.warn("'torch.load' received a zip file that looks like a To │
│ 780 │ │ │ │ │ │ │ │ " dispatching to 'torch.jit.load' (call 'torch.jit.loa │
│ │
│ E:\Anaconda3\envs\Fuck\lib\site-packages\torch\serialization.py:282 in init │
│ │
│ 279 │
│ 280 class _open_zipfile_reader(_opener): │
│ 281 │ def init(self, name_or_buffer) -> None: │
│ ❱ 282 │ │ super(_open_zipfile_reader, self).init(torch._C.PyTorchFileReader(name_or_bu │
│ 283 │
│ 284 │
│ 285 class _open_zipfile_writer_file(_opener): │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by ATheRinan** [comment]
What I did to fix that was literally deleting the tortoise and voicefixer folder in .cache and literally uninstalled and reinstalled everything with poetry and just left it afk for a while. But I'm a windows user so i dont know if that may apply to your situation other than I received the same problem with voicefixer dl stopped midway

**Comment by KaleidoscopicPrism** [comment]
> What I did to fix that was literally deleting the tortoise and voicefixer folder in .cache and literally uninstalled and reinstalled everything with poetry and just left it afk for a while. But I'm a windows user so i dont know if that may apply to your situation other than I received the same problem with voicefixer dl stopped midway

Would this work with anaconda?

**Comment by ATheRinan** [comment]
probably, I also had to delete the env when my poetry fuck ups, so you might need to delete the env in anaconda folder

**Comment by KaleidoscopicPrism** [comment]
i am unable to find the .cache folder and i am unable to find something which might feature the tortoise and voicefixer folder

**Comment by ATheRinan** [comment]
Its in the Users/%Username% /.cache folder
Where %Username% is your username on windows

**Comment by KaleidoscopicPrism** [comment]
thank
