### ISSUE TITLE
tortoise_tts.py: error: one of the arguments -l, --list-voices -P, --play -o, --output -O, --output-dir is required

### ISSUE THREAD

**Issue by tanfarou** [152334H/tortoise-tts-fast#42]
I'm unable to run via the tortoise_tts.py script. However, I could run do_tts.py as well as Streamlit. Not sure what I am doing wrong. I would appreciate any guidance you can give me. 
<img width="853" alt="Screenshot 2023-03-04 003546" src="https://user-images.githubusercontent.com/111169072/222880406-1fd788cf-9b7d-4d4d-af40-de072f831821.png">

**Comment by 152334H** [comment]
the script was changed to take text as a final output argument (e.g. `tortoise_tts.py "hello world"`), not as a specific flag
