### ISSUE TITLE
google colab 

### ISSUE THREAD

**Issue by willsionggg** [152334H/tortoise-tts-fast#44]
it was working fine but after this update  not anymore

/content/tortoise-tts-fast/tortoise/models/vocoder.py:10 in <module>                             │
│                                                                                                  │
│     7 from typing import Optional, Callable                                                      │
│     8 from dataclasses import dataclass                                                          │
│     9 try:                                                                                       │
│ ❱  10 │   from BigVGAN.models import BigVGAN as BVGModel                                         │
│    11 │   from BigVGAN.env import AttrDict                                                       │
│    12 except ImportError:                                                                        │
│    13 │   raise ImportError(                                                                     │
│                                                                                                  │
│ /content/BigVGAN/models.py:14 in <module>                                                        │
│                                                                                                  │
│    11 from torch.nn import Conv1d, ConvTranspose1d, Conv2d                                       │
│    12 from torch.nn.utils import weight_norm, remove_weight_norm, spectral_norm                  │
│    13                                                                                            │
│ ❱  14 import activations                                                                         │
│    15 from utils import init_weights, get_padding                                                │
│    16 from alias_free_torch import *                                                             │
│    17                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'activations'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py:3326 in run_code         │
│                                                                                                  │
│   3323 │   │   │   │   elif async_ :                                                             │
│   3324 │   │   │   │   │   await eval(code_obj, self.user_global_ns, self.user_ns)               │
│   3325 │   │   │   │   else:                                                                     │
│ ❱ 3326 │   │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                     │
│   3327 │   │   │   finally:                                                                      │
│   3328 │   │   │   │   # Reset our crash handler in place                                        │
│   3329 │   │   │   │   sys.excepthook = old_excepthook                                           │
│ in <module>                                                                                      │
│                                                                                                  │
│ /content/tortoise-tts-fast/tortoise/api.py:19 in <module>                                        │
│                                                                                                  │
│    16 from tortoise.models.cvvp import CVVP                                                      │
│    17 from tortoise.models.diffusion_decoder import DiffusionTts                                 │
│    18 from tortoise.models.random_latent_generator import RandomLatentConverter                  │
│ ❱  19 from tortoise.models.vocoder import VocConf                                                │
│    20 from tortoise.utils.audio import denormalize_tacotron_mel, wav_to_univnet_mel              │
│    21 from tortoise.utils.diffusion import (                                                     │
│    22 │   SpacedDiffusion,                                                                       │
│                                                                                                  │
│ /content/tortoise-tts-fast/tortoise/models/vocoder.py:13 in <module>                             │
│                                                                                                  │
│    10 │   from BigVGAN.models import BigVGAN as BVGModel                                         │
│    11 │   from BigVGAN.env import AttrDict                                                       │
│    12 except ImportError:                                                                        │
│ ❱  13 │   raise ImportError(                                                                     │
│    14 │   │   "BigVGAN not installed, can't use BigVGAN vocoder\n"                               │
│    15 │   │   "Please see the installation instructions on README."                              │
│    16 │   )                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: BigVGAN not installed, can't use BigVGAN vocoder
Please see the installation instructions on README.

**Comment by tanfarou** [comment]
Same issue on Windows local install.

**Comment by absane** [comment]
Solution:

```
cd BigVGAN
pip install -e .
cd ..
```

**Comment by willsionggg** [comment]
thank you it works
and one thing you will need to download  BigVGAN  from here https://github.com/152334H/BigVGAN/tree/61dc4d24650d0900e00705af4c3473e07112a989
as this repo contain empty file of  BigVGAN   don't know why  
anyway thank you for help

**Comment by absane** [comment]
> as this repo contain empty file of BigVGAN don't know why

That's because `git clone [url]` doesn't pull sub-modules by default. I believe you can do it with this command:

`git pull --recurse-submodules [url]`

**Comment by 152334H** [comment]
TIL about the differences between editable pip installations and normal package installations.

I have killed the submodule and correspondingly converted the BigVGAN fork to a real package. This should enable a fresh installation to work without error.
