### ISSUE TITLE
Trying to use the CLI again but have I got the syntax correct?

### ISSUE THREAD

**Issue by rikabi89** [152334H/tortoise-tts-fast#49]
So I've been using streamlit webui a while with no issues. I need to go back to CLI as I need to work on a large amount of text. Anyway I've been trying to synthesis text with or without the model checkpoint but I get "reading text from stdin!" and then nothing happens. I know this is under maintence but I appreciate if you could guide me here.

Below is the log.

```
(tts-fast2) H:\tortoise-tts-fast>python scripts/tortoise_tts.py --original_tortoise  --voice trump --preset ultra_fast --text "Well, you know, for starters, sponges are real organisms, right?"
reading text from stdin!
```

**Comment by 152334H** [comment]
remove --text

**Comment by rikabi89** [comment]
Thanks!
