### ISSUE TITLE
Training another language

### ISSUE THREAD

**Issue by Kamil-Roszak** [152334H/tortoise-tts-fast#5]
Hello, 
I have a large collection of voices for the Polish language - will it be possible to train / finetune my own model in the future?
The original Tortoise repository does not contain the code for training

**Comment by 152334H** [comment]
not unless I successfully recreate the VQVAE, which will not be done soon && will not be done in this repo if it happens

if I do eventually succeed in doing so, I would make a larger announcement so that you don't miss it

**Comment by bluusun** [comment]
Just a friendly ping - was there an announcement to provide Tortoise in another language?

**Comment by 152334H** [comment]
i've done a lot of different things over the past 4 months, none of which were related to this, sorry

consider this reply as the default reply for any other question on this repo
