### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by chrisbward** [152334H/tortoise-tts-fast#51]
```
./scripts/tortoise_tts.py --preset ultra_fast --text "testing this out"       
reading text from stdin!
```

and then just hangs, sits there doing nothing

**Comment by chrisbward** [comment]
https://github.com/152334H/tortoise-tts-fast/issues/49

command to run is;
```
./scripts/tortoise_tts.py --preset ultra_fast "testing this out"     
```
without --text

shame the docs aren't updated

Also, while we're here - change tortoise-tts.py to an underscore as above, scripts for script

**Comment by bluusun** [comment]
How to specify a text file input?

**Comment by eloop001** [comment]
use the less-than sign <
./scripts/tortoise_tts.py --preset ultra_fast<yourtextfile.txt

**Comment by dustinchen93** [comment]
> (tortoisetts) D:\apps\tortoise-tts-fast>python ./scripts/tortoise_tts.py --preset ultra_fast "testing this out"
> Loading tts...

hangs again after removing "text"
May I ask how long it would take to run a command like this?

**Comment by danielstepanek** [comment]
Also can't seem to get an output here. Just getting stuck on "Loading tts..."
 all my dependencies seem to be fine. Working with python 3.8.0rc1
