### ISSUE TITLE
Apostrophes

### ISSUE THREAD

**Issue by demonauthor** [152334H/tortoise-tts-fast#55]
It seems to convert apostrophes into a combination of characters:  "youâ€™ll"  instead of "you'll".

Then it reads those characters (as best it can). Is there a way to avoid this, other than editing every contraction in the file? Or do you just have to remove every contraction?

**Comment by xenotropic** [comment]
TorToiSe itself doesn't do any converting of text files. That sounds sort of like you have some sort of encoding problem between how your text file is encoded and the program you're viewing it with. If you continue to have problems with it, I think TorToiSe probably isn't paying much attention to the apostrophes anyway -- it will say you'll and youll the same -- so yo could write some string-replace script to remove them all if you continue to have problems.

**Comment by 152334H** [comment]
a [`RIGHT SINGLE QUOTATION MARK`](https://www.fileformat.info/info/unicode/char/2019/index.htm) is not an apostrophe

**Comment by 152334H** [comment]
a simple fix for this issue would be to run [unidecode](https://pypi.org/project/Unidecode/) on the input text
