### ISSUE TITLE
Do you want to just mainline this repo?

### ISSUE THREAD

**Issue by neonbjb** [152334H/tortoise-tts-fast#69]
This is impressive work, great job!

Do you want to just merge this back into tortoise-tts and become a maintainer? I don't have the time/will to implement features like these but I'd love to have some collaborators who do.

**Comment by 152334H** [comment]
As you might have noticed, I haven't significantly updated the fork in months. I don't even respond to issues here anymore (there are so many). I can click the PR button, but I really do not want to be a maintainer. 

I'm mentally done with TTS -- quit my job, quit this fork, quit my interest. There's so much more important things to work on, as I'm sure you'll believe... I'm happy to use and pay for whatever app your company releases in a month or two 😏

**Comment by neonbjb** [comment]
NP, just figured I'd ask. I get the sentiment and am in the same boat.
