### ISSUE TITLE
weird input voice sample treatment

### ISSUE THREAD

**Issue by hesz94** [152334H/tortoise-tts-fast#7]
1) According to the readme the voice samples for voice cloning HAVE TO be at 22.05kHz, but then the first thing done to them after loading is resampling them to 24kHz - should prolly switch up to inputting non-default sampling rate if we're resampling anyway

2) After reading the voice samples and resampling them, only first 102400 samples (~4.27s at 24kHz fs) are used to generate the latents - as far as I'm aware nothing stops us from either taking more samples, or looping the process over existing samples and averaging latents for the specific voice. Tried both approaches locally and they seemed to have increased voice stability (which makes sense since such averaged latents should be more representative of a voice profile).

**Comment by 152334H** [comment]
1. the specific line was created at [this commit](https://github.com/152334H/tortoise-tts-fast/tree/a064290559a4d28d4d778702232e7980e02a6db6), and subsequently never changed again. It shouldn't be hard for me to write code to read the sampling rate and adjust accordingly
2. That's extremely interesting; I have no idea how I'd go about doing that. If you're up for it, I'd gladly accept a PR, otherwise I can try to take a stab at it blindly myself

**Comment by hesz94** [comment]
Sure thing, I'll post it tomorrow

**Comment by 152334H** [comment]
> but then the first thing done to them after loading is resampling them to 24kHz

Where exactly did you find this? The call chain I'm seeing in `do_tts.py` is:

```python
load_voices(["name"]) -> load_voice("name", []) -> load_audio("./tortoise/voices/name/...", 22050) -> torchaudio.functional.resample(audio, lsr, 22050)
```
which seems to convert all audio files to 22.050kHz directly. Do I misunderstand?

**Comment by pepinu** [comment]
as for 1. if tortoise was trained on LJSpeech dataset, it may be an artefact of that: [LJSpeech Dataset](https://keithito.com/LJ-Speech-Dataset) - all samples within the dataset are prepared as 22.05kHz

nevertheless I've asked the author about this [here](https://github.com/neonbjb/tortoise-tts/issues/296)

**Comment by pepinu** [comment]
https://github.com/neonbjb/tortoise-tts/issues/296#issuecomment-1420295707

can be closed

**Comment by hesz94** [comment]
Added the expanded latent loading/averaging in #13
