### ISSUE TITLE
Install issue: can't install requirements.txt

### ISSUE THREAD

**Issue by crazygonuts** [152334H/tortoise-tts-fast#86]
pip3 install -r requirements.txt
Collecting bigvgan@ git+https://github.com/152334H/BigVGAN.git@HEAD (from -r requirements.txt (line 38))
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    bigvgan@ git+https://github.com/152334H/BigVGAN.git@HEAD from git+https://github.com/152334H/BigVGAN.git@HEAD (from -r requirements.txt (line 38))

Not sure how to get around this.

**Comment by crazygonuts** [comment]
closing because I eventually reinstalled enough times that it went away.

**Comment by zxcvqwerasdf** [comment]
don't install requirements.

python3 -m pip install -e . 
is enough.
