### ISSUE TITLE
Generating voice is really slow, doesn't seem to use the GPU at all, "Error: You set cuda=True but no cuda device could be found"

### ISSUE THREAD

**Issue by crazygonuts** [152334H/tortoise-tts-fast#87]
I can generate voice but its super slow.  Possibly related to this https://github.com/152334H/tortoise-tts-fast/issues/86 because I couldn't get requirements.txt to install.  I installed pytorch using conda and regular tortoise-tts works fine, its just tortoise-tts-fast that doesn't seem to know how to talk to the gfx card

**Comment by crazygonuts** [comment]
I tried downgrading as sepcified here https://github.com/152334H/tortoise-tts-fast/issues/9 with no effect

**Comment by crazygonuts** [comment]
closing because I eventually reinstalled enough times that it went away

**Comment by laperiut** [comment]
Hey CrazyGoNuts, what did you end up reinstalling?
The entire environment or just PyTorch ?

**Comment by crazygonuts** [comment]
the entire environment.  I followed this youtube guide the last time https://www.youtube.com/watch?v=8i4T5v1Fl_M but as far as I can tell it was exactly what I was already doing.
